### ISSUE TITLE
Explore docsy as a template for the site

### ISSUE THREAD

**Issue by vsoch** [sfosc/sfosc#109]
We currently have a "book" sort of format, which is challenging as it expects chapters, and thus grouping things into logical buckets. Not everything fits in a bucket! We'd like to explore other kinds of templates and options, so I'm going to take a stab at docsy. Please assign me to this issue.

**Comment by nothingismagick** [comment]
Look forward to becoming closer with more ~Google~ Open Source ~products~ Software
