### ISSUE TITLE
Redirect principles page

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#112]
In the previous theme, and as part of the raw social contracts text, we're referring to:
https://sfosc.org/principles

Currently that's a 404 as it's now in https://sfosc.org/docs/principles/
Perhaps we should set a redirect for this?
In hugo terms that would be an alias: https://gohugo.io/content-management/urls/#aliases

**Comment by nothingismagick** [comment]
OMG - yes, do that please ASAP!

**Comment by Beanow** [comment]
As requested, PR on #114
