### ISSUE TITLE
Is there a chat channel or mailing list that can be joined?

### ISSUE THREAD

**Issue by karianna** [sfosc/sfosc#21]
IRC / Mailing List / Whatever.  This is a very interesting project to follow!

**Comment by adamhjk** [comment]
Not yet! The folks at Sustain OSS are going to let us join their discourse, so that will help.

**Comment by adamhjk** [comment]
If you want to start an IRC channel or a mailing list, I'm happy to link to it!

**Comment by GeorgLink** [comment]
Here is the link to the forum: https://discourse.sustainoss.org/c/community/sfosc

**Comment by GeorgLink** [comment]
I propose to limit the number of communication channels and gather the community in one place.

**Comment by Beanow** [comment]
@karianna since most activity happens on the github repo here.
The best way to keep up to date currently is by [watching the repo](https://help.github.com/en/articles/watching-and-unwatching-repositories#watching-a-single-repository).

**Comment by nothingismagick** [comment]
We have been discussing the idea of having some kind of chat server like discord, but there haven't been any decisions about that. Thinking about it (and some of the other issues we've been talking about regarding Issues that we don't just want to close) maybe we could create a chat server and make channels for discussion topics that are unlikely to come to a resolution but are nevertheless valid points...

**Comment by karianna** [comment]
> @karianna since most activity happens on the github repo here.
> The best way to keep up to date currently is by [watching the repo](https://help.github.com/en/articles/watching-and-unwatching-repositories#watching-a-single-repository).

Got it thanks

**Comment by nothingismagick** [comment]
Don't forget to close the issue. Thank you 👍

>
