### ISSUE TITLE
MySQL business model

### ISSUE THREAD

**Issue by federico-razzoli** [sfosc/sfosc#35]
MySQL is only listed under "Dual licensing" business model. Actually the income from the proprietary licenses never been too significative for them, as far as I understand. Currently, I don't think they even do it: the "embedded server" library was discontinued starting from version 8.0, so I don't see any reason to buy a proprietary license.

Oracle, after the acquisition, introduced a loose open core model: some plugins are only available in the Enterprise Edition. However I doubt that many customers buy the EE mainly to use the plugins - as I understand, their primary business model must be Support.

**Comment by adamhjk** [comment]
Yes - even pre Oracle, they had at least a few pieces of proprietary kit (backups, if my memory serves). I put it in that category not because it didn’t have other models present, but because of all the historic trouble the scheme caused. Should I clarify further in the text?

**Comment by santec** [comment]
You're right - my memories of that period start to be foggy. But it was still a minor income, I think.

I think that clarifying would be good. Because in Support page, I read:
```
XenSource (very early on - moved to loose open core over time)
```
This could make the reader think that these are not just examples, but also valid information about what the companies currently do.

**Comment by adamhjk** [comment]
Makes sense. Do you want to take a pass at changing it and send a PR? 

Otherwise, I’m happy to.

**Comment by santec** [comment]
Yes, I can do a PR. Will do this during the holidays.

**Comment by adamhjk** [comment]
Hey great! Looking forward to it, @santec!

**Comment by santec** [comment]
Even if it's secondary, for the record MySQL still sells proprietary licenses:
https://www.mysql.com/about/legal/licensing/oem/

See MR #39

**Comment by federico-razzoli** [comment]
Will the MR be merged?

**Comment by Beanow** [comment]
Sorry for the long wait. The pull request has now gone in and can be previewed at
https://sfosc.org/preview
