### ISSUE TITLE
Any other examples of "Free Software Product" besides Redhat?

### ISSUE THREAD

**Issue by ryw** [sfosc/sfosc#37]
It's an appealing model, but I've been warned "only Red Hat can pull off" — are there newer, smaller companies using this model successfully?

**Comment by adamhjk** [comment]
I’ll be honest - I haven’t found one yet. I think that’s because:

1) everyone just takes the “support” part for granted
2) they give away a branded open source distribution (a CE edition, say), which dilutes the products value to zero. 

Like Lauren, I think more will be coming.

**Comment by ryw** [comment]
Thanks Adam + Lauren. 

We're thinking of putting all (or some) of our code into a new Github organization (ala Fedora) that doesn't share our branding. We then use this open-source base to build our branded commercial offerings, and if a robust user community develops around the open-source, that's ultimately a good thing for us long-term even though we will feel that we're missing some opportunities to monetize.

Scary decision :)
