### ISSUE TITLE
Volunteer maintainer

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#60]
Based on open pull requests, and the comment: https://github.com/sfosc/sfosc/pull/45#issuecomment-463720751

> I've been taking a bit of a break (I moved on from Chef after 10 years, so I've been playing a lot of video games and hanging around my house - it's a delight), so I'm way behind on looking at SFOSC.

It looks like @adamhjk is on a well earned break from maintainership.

As I find the original work insightful and inspiring, I'm personally eager to see him return and pick his brain on this subject. But at the same time believe it would make sense to have one or two more people on board with commit access to regain some momentum.

@adamhjk maybe you can update us on your preferences on maintaining sfosc.

I'm happy to volunteer and see what I can do here given a green light from @adamhjk and members. Of course acknowledging, I'm in no way an expert that could make opinionated judgement calls, ideally I'd like to co-maintain and see a couple of LGTM's before anything goes in by my hand.

**Comment by adamhjk** [comment]
Lets do it. Thank you so much for volunteering! :)

I'll add you to the repo.

**Comment by Beanow** [comment]
Thank you, and glad to see you back on the repo @adamhjk :smile:

Part two, I think is governance. My thinking is that either you should keep the final say on things as the project lead and I can pick up non-controversial maintainer tasks. Or if I'm to have more freedom to judge perhaps it's better to put that to a referendum, as the social contract / rules state.

What is your take on that?

**Comment by Beanow** [comment]
Let's take specifics of my role and governance to #70.
