### ISSUE TITLE
Introduction and maintainer role

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#70]
Hello SFOSC, it's a little overdue but let me share my background and intentions.

**Background**

My primary work so far has been in small business, web agencies and tech startups that don't have open source at the heart of their business. Preferring to work with small teams as they're a great place to break out of job descriptions and be involved with anything from strategic to hardware level, though mostly software.

Having enjoyed the FOSS freedoms and benefits privately and professionally I believe empowering others to solve their problems without nasty catches is an incredibly valuable contribution to make for the greater good.

In the same way probably all of you will be familiar with, trying to give back surfaced the usual hurdles. No budget, no time, lukewarm high-level commitment, having bills to pay, etc. Being at a career crossroads a month or two ago, I made a personal commitment to put more consistent contributions at the center of "what's next" for me. Which brought me to the FOSS sustainability debate and SFOSC.

**Intentions**

Seeing work here had slowed down and developed a backlog, I volunteered to help maintain (#60) in spite of not bringing in-depth experience of grand open source projects or open source centered businesses to the table. My intention being, to help out with SFOSC as a platform regaining momentum and push for the documents to reflect the community.

**Maintainer role**

As I've neither been elected [project lead](https://github.com/sfosc/sfosc/blob/master/RULES.md) nor have the experience to push an opinionated view, I have a strong preference to seek community approval for merges and not act or appear as an authority.

I'm happy to see @nothingismagick made a round of several github reviews and propose moving forward with making this the normal workflow.

Additionally, I believe there's room for additional maintainers to offer more continuity. So please do get in touch if you're willing to take this on as well. And when it comes to judgement calls I do make, I'm always open to feedback.

**Comment by nothingismagick** [comment]
Great to see you here and I've loved our exchanges to date!

I think its important to always have at least two reviews - especially when its about membership and such, and Pull Requestor can't review their own changes obviously. 

I could envision joining as co-maintainer, but would write my introduction separately outside of this issue. I'm generally pretty busy though and couldn't take on the responsibilities of project lead.

**Comment by Beanow** [comment]
> Great to see you here and I've loved our exchanges to date!

Likewise :smile: 

> I could envision joining as co-maintainer, but would write my introduction separately outside of this issue. I'm generally pretty busy though and couldn't take on the responsibilities of project lead.

Of course and same for me at the moment, so it's taking me some time to ramp up. All the more reason for me to make an open invite. People are already being greatly helpful and generous with their time, but our bus factor isn't where it could be yet. I'd be happy to co-maintain with you if you're feeling up for it :]

**Comment by nothingismagick** [comment]
Does this issue need to stay open?
