### ISSUE TITLE
Automate github pages build

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#79]
The current setup requires manual builds. It would be good to automate this step.

**Comment by Beanow** [comment]
@adamhjk currently I don't seem to have write access for the github pages repository.
But moreover I think we should add a [deploy key](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) and hook up this repo to a build platform like circle-ci.

I'll experiment with the setup on a fork to test.

**Comment by Beanow** [comment]
I've tinkered with my fork to set up automated builds on circle.
https://github.com/Beanow/sfosc/tree/example/circleci-build

It requires a deploy key using `ssh-keygen ./deploy_key`.
The public one `./deploy_key.pub` goes to GitHub.
https://github.com/sfosc/sfosc/settings/keys

The private one `./deploy_key` to CircleCI's project settings under SSH keys
https://circleci.com/gh/sfosc/sfosc/edit#ssh
Using `github.com` for the hostname.

Both github and circle will show a fingerprint. This will go into [`.circleci/config.yml`](https://github.com/Beanow/sfosc/blob/example/circleci-build/.circleci/config.yml)

**Comment by hennevogel** [comment]
Another option would be to move to https://www.netlify.com/ which will also get you deploy previews.

**Comment by Beanow** [comment]
@hennevogel that sounds like a cool feature, though currently I think github pages lowers the barriers for people who would like to fork vs an additional free-for-oss service which is more in line with SFOSC (for example #84 considers cost of forking). Since 'pages' has been implemented in oss like [gitlab](https://about.gitlab.com/product/pages/), I think it's more accessible to use as a standard.

If you know of a way netlify or an alternative could be replicated with self-hosted tools, I would be happy to consider it :]

**Comment by Beanow** [comment]
Actually in that sense, I would prefer https://drone.io/ as well over circle. Hadn't noticed they offer a free-for-oss cloud version. Need to have a look at building through that.

**Comment by hennevogel** [comment]
Netlify isn't a replacement for github or your static site generator. It's a replacement for the github pages feature (also not a oss tool). So to build the site for production or for your local dev-env you would still use hugo.

On here you would get PRs automatically deployed to a preview site (something like https://deploy-preview-79--sfosc.netlify.com), and commits to master would also be automatically deployed to the site.

**Comment by Beanow** [comment]
Ran a test with drone cloud as well. https://github.com/Beanow/sfosc-drone-cron
Interestingly though, drone recently moved to open-core. Agents to run a cluster have a non-commercial or 32 day trial license. https://github.com/drone/drone/blob/master/LICENSE
