### ISSUE TITLE
Co-maintainer

### ISSUE THREAD

**Issue by nothingismagick** [sfosc/sfosc#80]
I've been mulling the idea of becoming a co-maintainer of SFOSC in my spare time, especially in consideration of https://github.com/sfosc/sfosc/issues/60 - and today in conversation with @Beanow I decided that it does make sense. I can't promise to commit any amount of time, but I do read the PRs and issues when I can and respond to things where I feel comfortable and knowledgable enough to do so.

My recent experience of reviewing PRs to this repository shows me that I have an opinion that matters here and am both willing and able to constructively direct the conversation in order to achieve results that move this forward. And so for me it makes sense to have the technical role of maintainer. Would love know what you all think of that - especially @adamhjk - who we all really miss here...

**Comment by Beanow** [comment]
Already with regular helps it's great to have you here.

My preference from the start has been to co-maintain and not pushing my own views too strongly.
All for it, thanks again for offering :smile: :+1:

**Comment by nothingismagick** [comment]
@adamhjk - would love to know how you feel about this...

**Comment by Beanow** [comment]
Since you are on board now @nothingismagick, would you like to close this?
