### ISSUE TITLE
New preview (@next) URL

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#93]
As mentioned in #92

> We have seen that there is a great deal of new and useful content that has not yet been published in the front-facing website. We considered the opportunity to make a @next version in order to solicit feedback before the content gets "published" (and to temporarily sidestep the current permissions issues faced by the maintainer team in Adam's absence).

I've had a go at testing out whether this is possible, and pushed a build to https://github.com/sfosc/preview which you can see live at https://sfosc.org/preview/

Right now it looks like I'll have the necessary permissions to maintain this. Will look into automation as well.

What are your thoughts on this approach?
(And the name /preview? Though, most importantly the approach as a whole.)

**Comment by Beanow** [comment]
As part of #104 I'm proposing we remove the preview. Instead keeping sfosc.org up to date with the master branch.

**Comment by Beanow** [comment]
#104 is now merged, so I suggest we archive the preview.

**Comment by nothingismagick** [comment]
I agree.

**Comment by Beanow** [comment]
Going ahead with this as `/preview` has gone pretty stale now and the CI/CD pipeline for the main site is running well.

**Comment by Beanow** [comment]
Apparently archiving didn't implicitly disable github pages. So I've reverted to explicitly disable github pages and archived again.

It seems there may still be some cache in play as https://sfosc.org/preview/ still returns the preview. But all further pages seem to have gone now. I assume with an update to the main site or some cache expires this will clear too.

**Comment by Beanow** [comment]
With preview now archived. I'll be closing this.
