### ISSUE TITLE
Discord channel created, all be welcome!

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#94]
@nothingismagick just created the SFOSC discord for us.
You can join with this here link **https://discord.gg/nz5NC9q**

Still working on the setup, but we'll get there :]
Poke me or @nothingismagick to receive the `member` role if you're [a member](https://github.com/sfosc/sfosc/blob/master/MEMBERSHIP.md). It doesn't grant any special privileges there, but makes for easier mentioning of all members.

**Comment by vsoch** [comment]
Oh, neat! I think I used to use this for WoW. I'm not sure if I still have an account, but I'll poke around to see if I can figure that out :)

**Comment by Beanow** [comment]
Discord is now pretty visible in the readme. Closing this issue.
